package com.IMTFoods.DeliveryPartnerManagement.service.implementation;

import java.util.ArrayList;
import java.util.List;

import org.springframework.stereotype.Service;

import com.IMTFoods.DeliveryPartnerManagement.builder.DeliveryPartnerAssignmentBuilder;
import com.IMTFoods.DeliveryPartnerManagement.builder.DeliveryPartnerAssignmentResponseBuilder;
import com.IMTFoods.DeliveryPartnerManagement.dao.DeliveryAssignmentRepository;
import com.IMTFoods.DeliveryPartnerManagement.dao.DeliveryPartnerRepository;
import com.IMTFoods.DeliveryPartnerManagement.dto.DeliveryPartnerAssignmentRequestDto;
import com.IMTFoods.DeliveryPartnerManagement.dto.DeliveryPartnerAssignmentResponseDto;
import com.IMTFoods.DeliveryPartnerManagement.exception.DeliveryAssignmentIdNotFoundException;
import com.IMTFoods.DeliveryPartnerManagement.exception.DeliveryPartnerIdNotFoundException;
import com.IMTFoods.DeliveryPartnerManagement.model.DeliveryPartnerAssignments;
import com.IMTFoods.DeliveryPartnerManagement.model.DeliveryPartnerDetails;
import com.IMTFoods.DeliveryPartnerManagement.service.DeliveryPartnerAssignmentService;

@Service
public class DeliveryPartnerAssignmentServiceImplementation implements DeliveryPartnerAssignmentService{

	private final DeliveryAssignmentRepository deliveryAssignmentRepository;
	private final DeliveryPartnerRepository deliveryPartnerRepository;
	private final DeliveryPartnerAssignmentResponseBuilder deliveryPartnerAssignmentResponseBuilder;
	
	public DeliveryPartnerAssignmentServiceImplementation(DeliveryAssignmentRepository deliveryAssignmentRepository, DeliveryPartnerRepository deliveryPartnerRepository, DeliveryPartnerAssignmentResponseBuilder deliveryPartnerAssignmentResponseBuilder) {
		this.deliveryAssignmentRepository = deliveryAssignmentRepository;
		this.deliveryPartnerRepository = deliveryPartnerRepository;
		this.deliveryPartnerAssignmentResponseBuilder = deliveryPartnerAssignmentResponseBuilder;
	}

	@Override
	public DeliveryPartnerAssignmentResponseDto createDeliveryAssignment(
			DeliveryPartnerAssignmentRequestDto deliveryPartnerAssignmentRequestDto) {
		
		DeliveryPartnerAssignments deliveryPartnerAssignment = DeliveryPartnerAssignmentBuilder.buildDeliveryPartnerAssignmentFromDeliveryPartnerAssignmentRequestDto(deliveryPartnerAssignmentRequestDto);
		
		DeliveryPartnerDetails deliveryPartnerDetails = deliveryPartnerRepository.findById(deliveryPartnerAssignmentRequestDto.getDeliveryPartnerAssignmentRequestDtoDeliveryPartnerId()).orElseThrow( () -> new DeliveryPartnerIdNotFoundException("Invalid Delivery Partner Id"));
		deliveryPartnerAssignment.setDeliveryPartnerId(deliveryPartnerDetails);
		DeliveryPartnerAssignments savedDeliveryAssignment = deliveryAssignmentRepository.save(deliveryPartnerAssignment);
		DeliveryPartnerAssignmentResponseDto deliveryPartnerAssignmentResponseDto = deliveryPartnerAssignmentResponseBuilder.buildDeliveryPartnerAssignmentResponseDtoFromDeliveryPartnerAssignment(savedDeliveryAssignment);

		return deliveryPartnerAssignmentResponseDto;
	}

	@Override
	public DeliveryPartnerAssignmentResponseDto getDeliveryPartnerAssignmentById(long deliveryAssignmentId) {
		DeliveryPartnerAssignments deliveryPartnerAssignments = deliveryAssignmentRepository.findById(deliveryAssignmentId).orElseThrow( () -> new DeliveryAssignmentIdNotFoundException("Invalid Delivery Assignment Id"));
		DeliveryPartnerAssignmentResponseDto deliveryPartnerAssignmentResponseDto = deliveryPartnerAssignmentResponseBuilder.buildDeliveryPartnerAssignmentResponseDtoFromDeliveryPartnerAssignment(deliveryPartnerAssignments);
		
		return deliveryPartnerAssignmentResponseDto;
	}

	@Override
	public List<DeliveryPartnerAssignmentResponseDto> getAllDeliveryPartnerAssignment() {
		List<DeliveryPartnerAssignments> listOfDeliveryPartnerAssignmnents = deliveryAssignmentRepository.findAll();
		List<DeliveryPartnerAssignmentResponseDto> listOfDeliveryPartnerAssignmentResponseDto = deliveryPartnerAssignmentResponseBuilder.buildListOfDeliveryPartnerAssignmentResponseDtoFromDeliveryPartnerAssignment(listOfDeliveryPartnerAssignmnents);
		
		return listOfDeliveryPartnerAssignmentResponseDto;
	}

	@Override
	public List<DeliveryPartnerAssignmentResponseDto> createAllDeliveryAssignment(
			List<DeliveryPartnerAssignmentRequestDto> deliveryPartnerAssignmentRequestDtoList) {
		
		List<DeliveryPartnerAssignmentResponseDto> deliveryPartnerAssignmentResponseDtoList = new ArrayList<>();
		for(DeliveryPartnerAssignmentRequestDto deliveryPartnerAssignmentRequestDto : deliveryPartnerAssignmentRequestDtoList) {
			DeliveryPartnerAssignmentResponseDto deliveryPartnerAssignmentResponseDto = createDeliveryAssignment(deliveryPartnerAssignmentRequestDto);
			deliveryPartnerAssignmentResponseDtoList.add(deliveryPartnerAssignmentResponseDto);
		}
		return deliveryPartnerAssignmentResponseDtoList;
	}
	
	
}
