package com.IMTFoods.FoodOrderManagement.utils;

public enum OrderStatus {
	
	SUCCESSFUL,
	
	PROCESSING,
	
	FAILED,
	
	PENDING,
	
	WAITING_FOR_RESTAURANT_APPROVAL,
	
	PREPARING_ORDER,
	
	ORDER_PREPARED,
	
	WAITING_FOR_DELIVERY_PARTNER,
	
	ORDER_PICK_UP_BY_DELIVERY_PARTNER,
	
	ORDER_DELIVERED,
	
	ORDER_CANCELLED_BY_USER,
	
	ORDER_RETURNED_TO_RESTAURANT_DUE_TO_USER_CANCELLED,
	
	ORDER_RETURNED_TO_RESTAURANT_DUE_TO_USER_NOT_PICKING_ORDER_AS_DELIVERY_PARTNER_TRIED_TO_CONTACT
	
}
