package com.IMTFoods.DeliveryPartnerManagement.service;

import java.util.List;

import com.IMTFoods.DeliveryPartnerManagement.dto.DeliveryPartnerDetailsRequestDto;
import com.IMTFoods.DeliveryPartnerManagement.dto.DeliveryPartnerDetailsResponseDto;
import com.IMTFoods.DeliveryPartnerManagement.dto.DeliveryPartnerDetailsUpdateRequestDto;
import com.IMTFoods.DeliveryPartnerManagement.dto.DeliveryPartnerDetailsUpdateResponseDto;
import com.IMTFoods.DeliveryPartnerManagement.exception.NoDeliveryPartnerAvailableException;
import com.IMTFoods.DeliveryPartnerManagement.utils.CurrentStatus;

public interface DeliveryPartnerDetailsService {

	DeliveryPartnerDetailsResponseDto signIn(DeliveryPartnerDetailsRequestDto deliveryPartnerDetailsRequestDto);

	List<DeliveryPartnerDetailsResponseDto> signInAll(List<DeliveryPartnerDetailsRequestDto> deliveryPartnerDetailsRequestDtoList);

	DeliveryPartnerDetailsResponseDto getDeliveryPartnerDetailsById(long deliveryPartnerId);

	List<DeliveryPartnerDetailsResponseDto> getAllDeliveryPartnerDetails();

	void deleteDeliveryPartnerById(long deliveryPartnerId);

	DeliveryPartnerDetailsUpdateResponseDto updateDeliveryPartnerDetailsById(long deliveryPartnerId,
			DeliveryPartnerDetailsUpdateRequestDto deliveryPartnerDetailsUpdateRequestDto);

	DeliveryPartnerDetailsResponseDto getAvailableDeliveryPartnerDetails() throws NoDeliveryPartnerAvailableException;

	void updateDeliveryPartnerCurrentStatus(long deliveryPartnerId, CurrentStatus currentStatus);

	void updateDeliveryPartnerTotalDeliveryCount(long deliveryPartnerId);

	
	
}
